#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Access
No description available.
.PARAMETER VerificationMethod
No description available.
.OUTPUTS

AccessPolicyRuleApplicationSignOn<PSCustomObject>
#>

function Initialize-AccessPolicyRuleApplicationSignOn {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Access},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${VerificationMethod}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => AccessPolicyRuleApplicationSignOn' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "access" = ${Access}
            "verificationMethod" = ${VerificationMethod}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AccessPolicyRuleApplicationSignOn<PSCustomObject>

.DESCRIPTION

Convert from JSON to AccessPolicyRuleApplicationSignOn<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AccessPolicyRuleApplicationSignOn<PSCustomObject>
#>
function ConvertFrom-JsonToAccessPolicyRuleApplicationSignOn {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => AccessPolicyRuleApplicationSignOn' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AccessPolicyRuleApplicationSignOn
        $AllProperties = ("access", "verificationMethod")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "access"))) { #optional property not found
            $Access = $null
        } else {
            $Access = $JsonParameters.PSobject.Properties["access"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "verificationMethod"))) { #optional property not found
            $VerificationMethod = $null
        } else {
            $VerificationMethod = $JsonParameters.PSobject.Properties["verificationMethod"].value
        }

        $PSO = [PSCustomObject]@{
            "access" = ${Access}
            "verificationMethod" = ${VerificationMethod}
        }

        return $PSO
    }

}

