#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER AuthURL
No description available.
.PARAMETER Url
No description available.
.OUTPUTS

BasicApplicationSettingsApplication<PSCustomObject>
#>

function Initialize-BasicApplicationSettingsApplication {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AuthURL},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Url}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => BasicApplicationSettingsApplication' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "authURL" = ${AuthURL}
            "url" = ${Url}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to BasicApplicationSettingsApplication<PSCustomObject>

.DESCRIPTION

Convert from JSON to BasicApplicationSettingsApplication<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

BasicApplicationSettingsApplication<PSCustomObject>
#>
function ConvertFrom-JsonToBasicApplicationSettingsApplication {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => BasicApplicationSettingsApplication' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in BasicApplicationSettingsApplication
        $AllProperties = ("authURL", "url")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "authURL"))) { #optional property not found
            $AuthURL = $null
        } else {
            $AuthURL = $JsonParameters.PSobject.Properties["authURL"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "url"))) { #optional property not found
            $Url = $null
        } else {
            $Url = $JsonParameters.PSobject.Properties["url"].value
        }

        $PSO = [PSCustomObject]@{
            "authURL" = ${AuthURL}
            "url" = ${Url}
        }

        return $PSO
    }

}

