#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER LifecycleCreate
No description available.
.OUTPUTS

CapabilitiesCreateObject<PSCustomObject>
#>

function Initialize-CapabilitiesCreateObject {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${LifecycleCreate}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CapabilitiesCreateObject' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "lifecycleCreate" = ${LifecycleCreate}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CapabilitiesCreateObject<PSCustomObject>

.DESCRIPTION

Convert from JSON to CapabilitiesCreateObject<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CapabilitiesCreateObject<PSCustomObject>
#>
function ConvertFrom-JsonToCapabilitiesCreateObject {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CapabilitiesCreateObject' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CapabilitiesCreateObject
        $AllProperties = ("lifecycleCreate")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lifecycleCreate"))) { #optional property not found
            $LifecycleCreate = $null
        } else {
            $LifecycleCreate = $JsonParameters.PSobject.Properties["lifecycleCreate"].value
        }

        $PSO = [PSCustomObject]@{
            "lifecycleCreate" = ${LifecycleCreate}
        }

        return $PSO
    }

}

