#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum IdentityProviderPolicyProvider.

.DESCRIPTION

No description available.
#>

enum IdentityProviderPolicyProvider {
    # enum value: "ANY"
    ANY
    # enum value: "OKTA"
    OKTA
    # enum value: "SPECIFIC_IDP"
    SPECIFIC_IDP
}

