#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum LocationGranularity.

.DESCRIPTION

No description available.
#>

enum LocationGranularity {
    # enum value: "CITY"
    CITY
    # enum value: "COUNTRY"
    COUNTRY
    # enum value: "LAT_LONG"
    LAT_LONG
    # enum value: "SUBDIVISION"
    SUBDIVISION
}

