#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER AuthContext
No description available.
.PARAMETER Network
No description available.
.PARAMETER People
No description available.
.OUTPUTS

OktaSignOnPolicyRuleConditionsAllOf<PSCustomObject>
#>

function Initialize-OktaSignOnPolicyRuleConditionsAllOf {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AuthContext},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Network},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${People}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => OktaSignOnPolicyRuleConditionsAllOf' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "authContext" = ${AuthContext}
            "network" = ${Network}
            "people" = ${People}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to OktaSignOnPolicyRuleConditionsAllOf<PSCustomObject>

.DESCRIPTION

Convert from JSON to OktaSignOnPolicyRuleConditionsAllOf<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

OktaSignOnPolicyRuleConditionsAllOf<PSCustomObject>
#>
function ConvertFrom-JsonToOktaSignOnPolicyRuleConditionsAllOf {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => OktaSignOnPolicyRuleConditionsAllOf' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OktaSignOnPolicyRuleConditionsAllOf
        $AllProperties = ("authContext", "network", "people")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "authContext"))) { #optional property not found
            $AuthContext = $null
        } else {
            $AuthContext = $JsonParameters.PSobject.Properties["authContext"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "network"))) { #optional property not found
            $Network = $null
        } else {
            $Network = $JsonParameters.PSobject.Properties["network"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "people"))) { #optional property not found
            $People = $null
        } else {
            $People = $JsonParameters.PSobject.Properties["people"].value
        }

        $PSO = [PSCustomObject]@{
            "authContext" = ${AuthContext}
            "network" = ${Network}
            "people" = ${People}
        }

        return $PSO
    }

}

