#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER OptOutEmailUsers
No description available.
.PARAMETER Links
No description available.
.OUTPUTS

OrgOktaCommunicationSetting<PSCustomObject>
#>

function Initialize-OrgOktaCommunicationSetting {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${OptOutEmailUsers},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Collections.Hashtable]
        ${Links}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => OrgOktaCommunicationSetting' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "optOutEmailUsers" = ${OptOutEmailUsers}
            "_links" = ${Links}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to OrgOktaCommunicationSetting<PSCustomObject>

.DESCRIPTION

Convert from JSON to OrgOktaCommunicationSetting<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

OrgOktaCommunicationSetting<PSCustomObject>
#>
function ConvertFrom-JsonToOrgOktaCommunicationSetting {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => OrgOktaCommunicationSetting' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OrgOktaCommunicationSetting
        $AllProperties = ("optOutEmailUsers", "_links")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "optOutEmailUsers"))) { #optional property not found
            $OptOutEmailUsers = $null
        } else {
            $OptOutEmailUsers = $JsonParameters.PSobject.Properties["optOutEmailUsers"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "_links"))) { #optional property not found
            $Links = $null
        } else {
            $Links = $JsonParameters.PSobject.Properties["_links"].value
        }

        $PSO = [PSCustomObject]@{
            "optOutEmailUsers" = ${OptOutEmailUsers}
            "_links" = ${Links}
        }

        return $PSO
    }

}

