#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Self
No description available.
.OUTPUTS

PolicyRuleActionsEnroll<PSCustomObject>
#>

function Initialize-PolicyRuleActionsEnroll {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Self}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => PolicyRuleActionsEnroll' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "self" = ${Self}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PolicyRuleActionsEnroll<PSCustomObject>

.DESCRIPTION

Convert from JSON to PolicyRuleActionsEnroll<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PolicyRuleActionsEnroll<PSCustomObject>
#>
function ConvertFrom-JsonToPolicyRuleActionsEnroll {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => PolicyRuleActionsEnroll' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PolicyRuleActionsEnroll
        $AllProperties = ("self")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "self"))) { #optional property not found
            $Self = $null
        } else {
            $Self = $JsonParameters.PSobject.Properties["self"].value
        }

        $PSO = [PSCustomObject]@{
            "self" = ${Self}
        }

        return $PSO
    }

}

