#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum SessionAuthenticationMethod.

.DESCRIPTION

No description available.
#>

enum SessionAuthenticationMethod {
    # enum value: "fpt"
    fpt
    # enum value: "geo"
    geo
    # enum value: "hwk"
    hwk
    # enum value: "kba"
    kba
    # enum value: "mca"
    mca
    # enum value: "mfa"
    mfa
    # enum value: "otp"
    otp
    # enum value: "pwd"
    pwd
    # enum value: "sc"
    sc
    # enum value: "sms"
    sms
    # enum value: "swk"
    swk
    # enum value: "tel"
    tel
}

