#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum UserIdentifierMatchType.

.DESCRIPTION

No description available.
#>

enum UserIdentifierMatchType {
    # enum value: "CONTAINS"
    CONTAINS
    # enum value: "EQUALS"
    EQUALS
    # enum value: "EXPRESSION"
    EXPRESSION
    # enum value: "STARTS_WITH"
    STARTS_WITH
    # enum value: "SUFFIX"
    SUFFIX
}

