#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'Okta.PowerShell' -name 'OktaOktaApiTokenApi' {
    Context 'Get-OktaApiToken' {
        It 'Test Get-OktaApiToken' {
            #$TestResult = Get-OktaApiToken -ApiTokenId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-OktaListApiTokens' {
        It 'Test Invoke-OktaListApiTokens' {
            #$TestResult = Invoke-OktaListApiTokens -After "TEST_VALUE" -Limit "TEST_VALUE" -Q "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Revoke-OktaApiToken' {
        It 'Test Revoke-OktaApiToken' {
            #$TestResult = Revoke-OktaApiToken -ApiTokenId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Revoke-OktaCurrentApiToken' {
        It 'Test Revoke-OktaCurrentApiToken' {
            #$TestResult = Revoke-OktaCurrentApiToken
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
