#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'Okta.PowerShell' -name 'OktaOktaAuthenticatorApi' {
    Context 'Invoke-OktaActivateAuthenticator' {
        It 'Test Invoke-OktaActivateAuthenticator' {
            #$TestResult = Invoke-OktaActivateAuthenticator -AuthenticatorId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-OktaAuthenticator' {
        It 'Test New-OktaAuthenticator' {
            #$TestResult = New-OktaAuthenticator -Authenticator "TEST_VALUE" -Activate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-OktaDeactivateAuthenticator' {
        It 'Test Invoke-OktaDeactivateAuthenticator' {
            #$TestResult = Invoke-OktaDeactivateAuthenticator -AuthenticatorId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OktaAuthenticator' {
        It 'Test Get-OktaAuthenticator' {
            #$TestResult = Get-OktaAuthenticator -AuthenticatorId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-OktaListAuthenticators' {
        It 'Test Invoke-OktaListAuthenticators' {
            #$TestResult = Invoke-OktaListAuthenticators
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-OktaAuthenticator' {
        It 'Test Update-OktaAuthenticator' {
            #$TestResult = Update-OktaAuthenticator -AuthenticatorId "TEST_VALUE" -Authenticator "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
