#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER SharedSecret
No description available.
.OUTPUTS

CustomHotpUserFactorProfile<PSCustomObject>
#>

function Initialize-OktaCustomHotpUserFactorProfile {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SharedSecret}
    )

    Process {
        'Creating PSCustomObject: Okta.PowerShell => OktaCustomHotpUserFactorProfile' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "sharedSecret" = ${SharedSecret}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CustomHotpUserFactorProfile<PSCustomObject>

.DESCRIPTION

Convert from JSON to CustomHotpUserFactorProfile<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CustomHotpUserFactorProfile<PSCustomObject>
#>
function ConvertFrom-OktaJsonToCustomHotpUserFactorProfile {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: Okta.PowerShell => OktaCustomHotpUserFactorProfile' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OktaCustomHotpUserFactorProfile
        $AllProperties = ("sharedSecret")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sharedSecret"))) { #optional property not found
            $SharedSecret = $null
        } else {
            $SharedSecret = $JsonParameters.PSobject.Properties["sharedSecret"].value
        }

        $PSO = [PSCustomObject]@{
            "sharedSecret" = ${SharedSecret}
        }

        return $PSO
    }

}

