#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum EndUserDashboardTouchPointVariant.

.DESCRIPTION

No description available.
#>

enum EndUserDashboardTouchPointVariant {
    # enum value: "FULL_THEME"
    FULL_THEME
    # enum value: "LOGO_ON_FULL_WHITE_BACKGROUND"
    LOGO_ON_FULL_WHITE_BACKGROUND
    # enum value: "OKTA_DEFAULT"
    OKTA_DEFAULT
    # enum value: "WHITE_LOGO_BACKGROUND"
    WHITE_LOGO_BACKGROUND
}
