#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum GroupType.

.DESCRIPTION

No description available.
#>

enum GroupType {
    # enum value: "APP_GROUP"
    APP_GROUP
    # enum value: "BUILT_IN"
    BUILT_IN
    # enum value: "OKTA_GROUP"
    OKTA_GROUP
}
