#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum HostedPageType.

.DESCRIPTION

No description available.
#>

enum HostedPageType {
    # enum value: "EXTERNALLY_HOSTED"
    EXTERNALLY_HOSTED
    # enum value: "OKTA_DEFAULT"
    OKTA_DEFAULT
}

