#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Kid
No description available.
.OUTPUTS

IdentityProviderCredentialsSigning<PSCustomObject>
#>

function Initialize-OktaIdentityProviderCredentialsSigning {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Kid}
    )

    Process {
        'Creating PSCustomObject: Okta.PowerShell => OktaIdentityProviderCredentialsSigning' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "kid" = ${Kid}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to IdentityProviderCredentialsSigning<PSCustomObject>

.DESCRIPTION

Convert from JSON to IdentityProviderCredentialsSigning<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

IdentityProviderCredentialsSigning<PSCustomObject>
#>
function ConvertFrom-OktaJsonToIdentityProviderCredentialsSigning {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: Okta.PowerShell => OktaIdentityProviderCredentialsSigning' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OktaIdentityProviderCredentialsSigning
        $AllProperties = ("kid")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "kid"))) { #optional property not found
            $Kid = $null
        } else {
            $Kid = $JsonParameters.PSobject.Properties["kid"].value
        }

        $PSO = [PSCustomObject]@{
            "kid" = ${Kid}
        }

        return $PSO
    }

}

