#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Methods
No description available.
.PARAMETER ReauthenticateIn
No description available.
.PARAMETER Types
No description available.
.OUTPUTS

KnowledgeConstraint<PSCustomObject>
#>

function Initialize-OktaKnowledgeConstraint {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Methods},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ReauthenticateIn},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Types}
    )

    Process {
        'Creating PSCustomObject: Okta.PowerShell => OktaKnowledgeConstraint' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "methods" = ${Methods}
            "reauthenticateIn" = ${ReauthenticateIn}
            "types" = ${Types}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to KnowledgeConstraint<PSCustomObject>

.DESCRIPTION

Convert from JSON to KnowledgeConstraint<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

KnowledgeConstraint<PSCustomObject>
#>
function ConvertFrom-OktaJsonToKnowledgeConstraint {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: Okta.PowerShell => OktaKnowledgeConstraint' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OktaKnowledgeConstraint
        $AllProperties = ("methods", "reauthenticateIn", "types")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "methods"))) { #optional property not found
            $Methods = $null
        } else {
            $Methods = $JsonParameters.PSobject.Properties["methods"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "reauthenticateIn"))) { #optional property not found
            $ReauthenticateIn = $null
        } else {
            $ReauthenticateIn = $JsonParameters.PSobject.Properties["reauthenticateIn"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "types"))) { #optional property not found
            $Types = $null
        } else {
            $Types = $JsonParameters.PSobject.Properties["types"].value
        }

        $PSO = [PSCustomObject]@{
            "methods" = ${Methods}
            "reauthenticateIn" = ${ReauthenticateIn}
            "types" = ${Types}
        }

        return $PSO
    }

}

