#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum MDMEnrollmentPolicyEnrollment.

.DESCRIPTION

No description available.
#>

enum MDMEnrollmentPolicyEnrollment {
    # enum value: "ANY_OR_NONE"
    ANY_OR_NONE
    # enum value: "OMM"
    OMM
}
