#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Options
No description available.
.OUTPUTS

PasswordPolicyDelegationSettings<PSCustomObject>
#>

function Initialize-OktaPasswordPolicyDelegationSettings {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Options}
    )

    Process {
        'Creating PSCustomObject: Okta.PowerShell => OktaPasswordPolicyDelegationSettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "options" = ${Options}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PasswordPolicyDelegationSettings<PSCustomObject>

.DESCRIPTION

Convert from JSON to PasswordPolicyDelegationSettings<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PasswordPolicyDelegationSettings<PSCustomObject>
#>
function ConvertFrom-OktaJsonToPasswordPolicyDelegationSettings {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: Okta.PowerShell => OktaPasswordPolicyDelegationSettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OktaPasswordPolicyDelegationSettings
        $AllProperties = ("options")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "options"))) { #optional property not found
            $Options = $null
        } else {
            $Options = $JsonParameters.PSobject.Properties["options"].value
        }

        $PSO = [PSCustomObject]@{
            "options" = ${Options}
        }

        return $PSO
    }

}

