#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum Platform.

.DESCRIPTION

No description available.
#>

enum Platform {
    # enum value: "ANDROID"
    ANDROID
    # enum value: "IOS"
    IOS
    # enum value: "MACOS"
    MACOS
    # enum value: "WINDOWS"
    WINDOWS
}

