#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Action
No description available.
.OUTPUTS

ProvisioningDeprovisionedCondition<PSCustomObject>
#>

function Initialize-OktaProvisioningDeprovisionedCondition {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("NONE", "REACTIVATE")]
        [PSCustomObject]
        ${Action}
    )

    Process {
        'Creating PSCustomObject: Okta.PowerShell => OktaProvisioningDeprovisionedCondition' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "action" = ${Action}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ProvisioningDeprovisionedCondition<PSCustomObject>

.DESCRIPTION

Convert from JSON to ProvisioningDeprovisionedCondition<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ProvisioningDeprovisionedCondition<PSCustomObject>
#>
function ConvertFrom-OktaJsonToProvisioningDeprovisionedCondition {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: Okta.PowerShell => OktaProvisioningDeprovisionedCondition' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OktaProvisioningDeprovisionedCondition
        $AllProperties = ("action")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "action"))) { #optional property not found
            $Action = $null
        } else {
            $Action = $JsonParameters.PSobject.Properties["action"].value
        }

        $PSO = [PSCustomObject]@{
            "action" = ${Action}
        }

        return $PSO
    }

}

