#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum SessionStatus.

.DESCRIPTION

No description available.
#>

enum SessionStatus {
    # enum value: "ACTIVE"
    ACTIVE
    # enum value: "MFA_ENROLL"
    MFA_ENROLL
    # enum value: "MFA_REQUIRED"
    MFA_REQUIRED
}

