#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Enabled
No description available.
.PARAMETER Issuer
No description available.
.PARAMETER LogoutUrl
No description available.
.OUTPUTS

SingleLogout<PSCustomObject>
#>

function Initialize-OktaSingleLogout {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Enabled},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Issuer},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${LogoutUrl}
    )

    Process {
        'Creating PSCustomObject: Okta.PowerShell => OktaSingleLogout' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "enabled" = ${Enabled}
            "issuer" = ${Issuer}
            "logoutUrl" = ${LogoutUrl}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SingleLogout<PSCustomObject>

.DESCRIPTION

Convert from JSON to SingleLogout<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SingleLogout<PSCustomObject>
#>
function ConvertFrom-OktaJsonToSingleLogout {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: Okta.PowerShell => OktaSingleLogout' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OktaSingleLogout
        $AllProperties = ("enabled", "issuer", "logoutUrl")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enabled"))) { #optional property not found
            $Enabled = $null
        } else {
            $Enabled = $JsonParameters.PSobject.Properties["enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "issuer"))) { #optional property not found
            $Issuer = $null
        } else {
            $Issuer = $JsonParameters.PSobject.Properties["issuer"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "logoutUrl"))) { #optional property not found
            $LogoutUrl = $null
        } else {
            $LogoutUrl = $JsonParameters.PSobject.Properties["logoutUrl"].value
        }

        $PSO = [PSCustomObject]@{
            "enabled" = ${Enabled}
            "issuer" = ${Issuer}
            "logoutUrl" = ${LogoutUrl}
        }

        return $PSO
    }

}

