#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER AllowedOktaApps
No description available.
.PARAMETER Type
No description available.
.OUTPUTS

TrustedOriginScope<PSCustomObject>
#>

function Initialize-OktaTrustedOriginScope {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${AllowedOktaApps},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("CORS", "IFRAME_EMBED", "REDIRECT")]
        [PSCustomObject]
        ${Type}
    )

    Process {
        'Creating PSCustomObject: Okta.PowerShell => OktaTrustedOriginScope' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "allowedOktaApps" = ${AllowedOktaApps}
            "type" = ${Type}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to TrustedOriginScope<PSCustomObject>

.DESCRIPTION

Convert from JSON to TrustedOriginScope<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

TrustedOriginScope<PSCustomObject>
#>
function ConvertFrom-OktaJsonToTrustedOriginScope {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: Okta.PowerShell => OktaTrustedOriginScope' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OktaTrustedOriginScope
        $AllProperties = ("allowedOktaApps", "type")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "allowedOktaApps"))) { #optional property not found
            $AllowedOktaApps = $null
        } else {
            $AllowedOktaApps = $JsonParameters.PSobject.Properties["allowedOktaApps"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        $PSO = [PSCustomObject]@{
            "allowedOktaApps" = ${AllowedOktaApps}
            "type" = ${Type}
        }

        return $PSO
    }

}

