#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AccessPolicyConstraint' {
    Context 'AccessPolicyConstraint' {
        It 'Initialize-AccessPolicyConstraint' {
            # a simple test to create an object
            #$NewObject = Initialize-AccessPolicyConstraint -Methods "TEST_VALUE" -ReauthenticateIn "TEST_VALUE" -Types "TEST_VALUE"
            #$NewObject | Should -BeOfType AccessPolicyConstraint
            #$NewObject.property | Should -Be 0
        }
    }
}
