#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'Agent' {
    Context 'Agent' {
        It 'Initialize-Agent' {
            # a simple test to create an object
            #$NewObject = Initialize-Agent -Id "TEST_VALUE" -IsHidden "TEST_VALUE" -IsLatestGAedVersion "TEST_VALUE" -LastConnection "TEST_VALUE" -Name "TEST_VALUE" -OperationalStatus "TEST_VALUE" -PoolId "TEST_VALUE" -Type "TEST_VALUE" -UpdateMessage "TEST_VALUE" -UpdateStatus "TEST_VALUE" -Version "TEST_VALUE" -Links "TEST_VALUE"
            #$NewObject | Should -BeOfType Agent
            #$NewObject.property | Should -Be 0
        }
    }
}
