#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'APNSConfiguration' {
    Context 'APNSConfiguration' {
        It 'Initialize-APNSConfiguration' {
            # a simple test to create an object
            #$NewObject = Initialize-APNSConfiguration -FileName "TEST_VALUE" -KeyId "TEST_VALUE" -TeamId "TEST_VALUE" -TokenSigningKey "TEST_VALUE"
            #$NewObject | Should -BeOfType APNSConfiguration
            #$NewObject.property | Should -Be 0
        }
    }
}
