#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AuthorizationServerPolicyRuleConditionsAllOf' {
    Context 'AuthorizationServerPolicyRuleConditionsAllOf' {
        It 'Initialize-AuthorizationServerPolicyRuleConditionsAllOf' {
            # a simple test to create an object
            #$NewObject = Initialize-AuthorizationServerPolicyRuleConditionsAllOf -Clients "TEST_VALUE" -GrantTypes "TEST_VALUE" -People "TEST_VALUE" -Scopes "TEST_VALUE"
            #$NewObject | Should -BeOfType AuthorizationServerPolicyRuleConditionsAllOf
            #$NewObject.property | Should -Be 0
        }
    }
}
