#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AutoLoginApplicationSettings' {
    Context 'AutoLoginApplicationSettings' {
        It 'Initialize-AutoLoginApplicationSettings' {
            # a simple test to create an object
            #$NewObject = Initialize-AutoLoginApplicationSettings -IdentityStoreId "TEST_VALUE" -ImplicitAssignment "TEST_VALUE" -InlineHookId "TEST_VALUE" -Notes "TEST_VALUE" -Notifications "TEST_VALUE" -SignOn "TEST_VALUE"
            #$NewObject | Should -BeOfType AutoLoginApplicationSettings
            #$NewObject.property | Should -Be 0
        }
    }
}
