#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AutoLoginApplicationSettingsAllOf' {
    Context 'AutoLoginApplicationSettingsAllOf' {
        It 'Initialize-AutoLoginApplicationSettingsAllOf' {
            # a simple test to create an object
            #$NewObject = Initialize-AutoLoginApplicationSettingsAllOf -SignOn "TEST_VALUE"
            #$NewObject | Should -BeOfType AutoLoginApplicationSettingsAllOf
            #$NewObject.property | Should -Be 0
        }
    }
}
