#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'BasicApplicationSettingsAllOf' {
    Context 'BasicApplicationSettingsAllOf' {
        It 'Initialize-BasicApplicationSettingsAllOf' {
            # a simple test to create an object
            #$NewObject = Initialize-BasicApplicationSettingsAllOf -App "TEST_VALUE"
            #$NewObject | Should -BeOfType BasicApplicationSettingsAllOf
            #$NewObject.property | Should -Be 0
        }
    }
}
