#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'BehaviorRuleAnomalousIPAllOf' {
    Context 'BehaviorRuleAnomalousIPAllOf' {
        It 'Initialize-BehaviorRuleAnomalousIPAllOf' {
            # a simple test to create an object
            #$NewObject = Initialize-BehaviorRuleAnomalousIPAllOf -Settings "TEST_VALUE"
            #$NewObject | Should -BeOfType BehaviorRuleAnomalousIPAllOf
            #$NewObject.property | Should -Be 0
        }
    }
}
