#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CAPTCHAInstance' {
    Context 'CAPTCHAInstance' {
        It 'Initialize-CAPTCHAInstance' {
            # a simple test to create an object
            #$NewObject = Initialize-CAPTCHAInstance -Id "TEST_VALUE" -Name "TEST_VALUE" -SecretKey "TEST_VALUE" -SiteKey "TEST_VALUE" -Type "TEST_VALUE" -Links "TEST_VALUE"
            #$NewObject | Should -BeOfType CAPTCHAInstance
            #$NewObject.property | Should -Be 0
        }
    }
}
