#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'DeviceLinks' {
    Context 'DeviceLinks' {
        It 'Initialize-DeviceLinks' {
            # a simple test to create an object
            #$NewObject = Initialize-DeviceLinks -Self "TEST_VALUE" -Users "TEST_VALUE" -Activate "TEST_VALUE" -Deactivate "TEST_VALUE" -Suspend "TEST_VALUE" -Unsuspend "TEST_VALUE"
            #$NewObject | Should -BeOfType DeviceLinks
            #$NewObject.property | Should -Be 0
        }
    }
}
