#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'EmailUserFactorAllOf' {
    Context 'EmailUserFactorAllOf' {
        It 'Initialize-EmailUserFactorAllOf' {
            # a simple test to create an object
            #$NewObject = Initialize-EmailUserFactorAllOf -VarProfile "TEST_VALUE"
            #$NewObject | Should -BeOfType EmailUserFactorAllOf
            #$NewObject.property | Should -Be 0
        }
    }
}
