#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'EmailDomain' {
    Context 'EmailDomain' {
        It 'Initialize-EmailDomain' {
            # a simple test to create an object
            #$NewObject = Initialize-EmailDomain -Domain "TEST_VALUE" -DisplayName "TEST_VALUE" -UserName "TEST_VALUE"
            #$NewObject | Should -BeOfType EmailDomain
            #$NewObject.property | Should -Be 0
        }
    }
}
