#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'EventHookChannel' {
    Context 'EventHookChannel' {
        It 'Initialize-EventHookChannel' {
            # a simple test to create an object
            #$NewObject = Initialize-EventHookChannel -Config "TEST_VALUE" -Type "TEST_VALUE" -Version "TEST_VALUE"
            #$NewObject | Should -BeOfType EventHookChannel
            #$NewObject.property | Should -Be 0
        }
    }
}
