#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'FCMPushProviderAllOf' {
    Context 'FCMPushProviderAllOf' {
        It 'Initialize-FCMPushProviderAllOf' {
            # a simple test to create an object
            #$NewObject = Initialize-FCMPushProviderAllOf -Configuration "TEST_VALUE"
            #$NewObject | Should -BeOfType FCMPushProviderAllOf
            #$NewObject.property | Should -Be 0
        }
    }
}
