#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'HardwareUserFactorProfile' {
    Context 'HardwareUserFactorProfile' {
        It 'Initialize-HardwareUserFactorProfile' {
            # a simple test to create an object
            #$NewObject = Initialize-HardwareUserFactorProfile -CredentialId "TEST_VALUE"
            #$NewObject | Should -BeOfType HardwareUserFactorProfile
            #$NewObject.property | Should -Be 0
        }
    }
}
