#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'HostedPageType' {
    Context 'HostedPageType' {
        It 'Initialize-HostedPageType' {
            # a simple test to create an object
            #$NewObject = Initialize-HostedPageType
            #$NewObject | Should -BeOfType HostedPageType
            #$NewObject.property | Should -Be 0
        }
    }
}
