#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'InlineHookChannelHttp' {
    Context 'InlineHookChannelHttp' {
        It 'Initialize-InlineHookChannelHttp' {
            # a simple test to create an object
            #$NewObject = Initialize-InlineHookChannelHttp -Type "TEST_VALUE" -Version "TEST_VALUE" -Config "TEST_VALUE"
            #$NewObject | Should -BeOfType InlineHookChannelHttp
            #$NewObject.property | Should -Be 0
        }
    }
}
