#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'InlineHookChannelConfigAuthScheme' {
    Context 'InlineHookChannelConfigAuthScheme' {
        It 'Initialize-InlineHookChannelConfigAuthScheme' {
            # a simple test to create an object
            #$NewObject = Initialize-InlineHookChannelConfigAuthScheme -Key "TEST_VALUE" -Type "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType InlineHookChannelConfigAuthScheme
            #$NewObject.property | Should -Be 0
        }
    }
}
