#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'LogStreamSchema' {
    Context 'LogStreamSchema' {
        It 'Initialize-LogStreamSchema' {
            # a simple test to create an object
            #$NewObject = Initialize-LogStreamSchema -Schema "TEST_VALUE" -Created "TEST_VALUE" -ErrorMessage "TEST_VALUE" -Id "TEST_VALUE" -LastUpdated "TEST_VALUE" -Name "TEST_VALUE" -Properties "TEST_VALUE" -Required "TEST_VALUE" -Title "TEST_VALUE" -Type "TEST_VALUE" -Links "TEST_VALUE"
            #$NewObject | Should -BeOfType LogStreamSchema
            #$NewObject.property | Should -Be 0
        }
    }
}
