#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'LogStreamAws' {
    Context 'LogStreamAws' {
        It 'Initialize-LogStreamAws' {
            # a simple test to create an object
            #$NewObject = Initialize-LogStreamAws -Created "TEST_VALUE" -Id "TEST_VALUE" -LastUpdated "TEST_VALUE" -Name "TEST_VALUE" -Status "TEST_VALUE" -Type "TEST_VALUE" -Links "TEST_VALUE" -Settings "TEST_VALUE"
            #$NewObject | Should -BeOfType LogStreamAws
            #$NewObject.property | Should -Be 0
        }
    }
}
