#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'MultifactorEnrollmentPolicyAuthenticatorSettings' {
    Context 'MultifactorEnrollmentPolicyAuthenticatorSettings' {
        It 'Initialize-MultifactorEnrollmentPolicyAuthenticatorSettings' {
            # a simple test to create an object
            #$NewObject = Initialize-MultifactorEnrollmentPolicyAuthenticatorSettings -Enroll "TEST_VALUE" -Key "TEST_VALUE"
            #$NewObject | Should -BeOfType MultifactorEnrollmentPolicyAuthenticatorSettings
            #$NewObject.property | Should -Be 0
        }
    }
}
