#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NotificationType' {
    Context 'NotificationType' {
        It 'Initialize-NotificationType' {
            # a simple test to create an object
            #$NewObject = Initialize-NotificationType
            #$NewObject | Should -BeOfType NotificationType
            #$NewObject.property | Should -Be 0
        }
    }
}
