#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OAuth2ScopeConsentGrant' {
    Context 'OAuth2ScopeConsentGrant' {
        It 'Initialize-OAuth2ScopeConsentGrant' {
            # a simple test to create an object
            #$NewObject = Initialize-OAuth2ScopeConsentGrant -ClientId "TEST_VALUE" -Created "TEST_VALUE" -CreatedBy "TEST_VALUE" -Id "TEST_VALUE" -Issuer "TEST_VALUE" -LastUpdated "TEST_VALUE" -ScopeId "TEST_VALUE" -Source "TEST_VALUE" -Status "TEST_VALUE" -UserId "TEST_VALUE" -Embedded "TEST_VALUE" -Links "TEST_VALUE"
            #$NewObject | Should -BeOfType OAuth2ScopeConsentGrant
            #$NewObject.property | Should -Be 0
        }
    }
}
