#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OAuth2ClaimConditions' {
    Context 'OAuth2ClaimConditions' {
        It 'Initialize-OAuth2ClaimConditions' {
            # a simple test to create an object
            #$NewObject = Initialize-OAuth2ClaimConditions -Scopes "TEST_VALUE"
            #$NewObject | Should -BeOfType OAuth2ClaimConditions
            #$NewObject.property | Should -Be 0
        }
    }
}
