#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OktaSignOnPolicyRuleSignonSessionActions' {
    Context 'OktaSignOnPolicyRuleSignonSessionActions' {
        It 'Initialize-OktaSignOnPolicyRuleSignonSessionActions' {
            # a simple test to create an object
            #$NewObject = Initialize-OktaSignOnPolicyRuleSignonSessionActions -MaxSessionIdleMinutes "TEST_VALUE" -MaxSessionLifetimeMinutes "TEST_VALUE" -UsePersistentCookie "TEST_VALUE"
            #$NewObject | Should -BeOfType OktaSignOnPolicyRuleSignonSessionActions
            #$NewObject.property | Should -Be 0
        }
    }
}
