#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OktaSignOnPolicyRuleSignonActions' {
    Context 'OktaSignOnPolicyRuleSignonActions' {
        It 'Initialize-OktaSignOnPolicyRuleSignonActions' {
            # a simple test to create an object
            #$NewObject = Initialize-OktaSignOnPolicyRuleSignonActions -Access "TEST_VALUE" -FactorLifetime "TEST_VALUE" -FactorPromptMode "TEST_VALUE" -RememberDeviceByDefault "TEST_VALUE" -RequireFactor "TEST_VALUE" -Session "TEST_VALUE"
            #$NewObject | Should -BeOfType OktaSignOnPolicyRuleSignonActions
            #$NewObject.property | Should -Be 0
        }
    }
}
