#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OktaSignOnPolicyRule' {
    Context 'OktaSignOnPolicyRule' {
        It 'Initialize-OktaSignOnPolicyRule' {
            # a simple test to create an object
            #$NewObject = Initialize-OktaSignOnPolicyRule -Created "TEST_VALUE" -Id "TEST_VALUE" -LastUpdated "TEST_VALUE" -Name "TEST_VALUE" -Priority "TEST_VALUE" -Status "TEST_VALUE" -System "TEST_VALUE" -Type "TEST_VALUE" -Actions "TEST_VALUE" -Conditions "TEST_VALUE"
            #$NewObject | Should -BeOfType OktaSignOnPolicyRule
            #$NewObject.property | Should -Be 0
        }
    }
}
