#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PageRootLinks' {
    Context 'PageRootLinks' {
        It 'Initialize-PageRootLinks' {
            # a simple test to create an object
            #$NewObject = Initialize-PageRootLinks -Self "TEST_VALUE" -Default "TEST_VALUE" -Customized "TEST_VALUE" -Preview "TEST_VALUE"
            #$NewObject | Should -BeOfType PageRootLinks
            #$NewObject.property | Should -Be 0
        }
    }
}
