#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PasswordPolicyRuleActionsAllOf' {
    Context 'PasswordPolicyRuleActionsAllOf' {
        It 'Initialize-PasswordPolicyRuleActionsAllOf' {
            # a simple test to create an object
            #$NewObject = Initialize-PasswordPolicyRuleActionsAllOf -PasswordChange "TEST_VALUE" -SelfServicePasswordReset "TEST_VALUE" -SelfServiceUnlock "TEST_VALUE"
            #$NewObject | Should -BeOfType PasswordPolicyRuleActionsAllOf
            #$NewObject.property | Should -Be 0
        }
    }
}
