#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PasswordPolicyPasswordSettingsLockout' {
    Context 'PasswordPolicyPasswordSettingsLockout' {
        It 'Initialize-PasswordPolicyPasswordSettingsLockout' {
            # a simple test to create an object
            #$NewObject = Initialize-PasswordPolicyPasswordSettingsLockout -AutoUnlockMinutes "TEST_VALUE" -MaxAttempts "TEST_VALUE" -ShowLockoutFailures "TEST_VALUE" -UserLockoutNotificationChannels "TEST_VALUE"
            #$NewObject | Should -BeOfType PasswordPolicyPasswordSettingsLockout
            #$NewObject.property | Should -Be 0
        }
    }
}
