#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PasswordPolicyConditions' {
    Context 'PasswordPolicyConditions' {
        It 'Initialize-PasswordPolicyConditions' {
            # a simple test to create an object
            #$NewObject = Initialize-PasswordPolicyConditions -App "TEST_VALUE" -Apps "TEST_VALUE" -AuthContext "TEST_VALUE" -AuthProvider "TEST_VALUE" -BeforeScheduledAction "TEST_VALUE" -Clients "TEST_VALUE" -Context "TEST_VALUE" -Device "TEST_VALUE" -GrantTypes "TEST_VALUE" -Groups "TEST_VALUE" -IdentityProvider "TEST_VALUE" -MdmEnrollment "TEST_VALUE" -Network "TEST_VALUE" -People "TEST_VALUE" -Platform "TEST_VALUE" -Risk "TEST_VALUE" -RiskScore "TEST_VALUE" -Scopes "TEST_VALUE" -UserIdentifier "TEST_VALUE" -Users "TEST_VALUE" -UserStatus "TEST_VALUE"
            #$NewObject | Should -BeOfType PasswordPolicyConditions
            #$NewObject.property | Should -Be 0
        }
    }
}
