#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PasswordPolicyRecoveryQuestion' {
    Context 'PasswordPolicyRecoveryQuestion' {
        It 'Initialize-PasswordPolicyRecoveryQuestion' {
            # a simple test to create an object
            #$NewObject = Initialize-PasswordPolicyRecoveryQuestion -Properties "TEST_VALUE" -Status "TEST_VALUE"
            #$NewObject | Should -BeOfType PasswordPolicyRecoveryQuestion
            #$NewObject.property | Should -Be 0
        }
    }
}
