#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PolicyAccountLink' {
    Context 'PolicyAccountLink' {
        It 'Initialize-PolicyAccountLink' {
            # a simple test to create an object
            #$NewObject = Initialize-PolicyAccountLink -Action "TEST_VALUE" -VarFilter "TEST_VALUE"
            #$NewObject | Should -BeOfType PolicyAccountLink
            #$NewObject.property | Should -Be 0
        }
    }
}
