#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PrincipalRateLimitEntity' {
    Context 'PrincipalRateLimitEntity' {
        It 'Initialize-PrincipalRateLimitEntity' {
            # a simple test to create an object
            #$NewObject = Initialize-PrincipalRateLimitEntity -CreatedBy "TEST_VALUE" -CreatedDate "TEST_VALUE" -DefaultConcurrencyPercentage "TEST_VALUE" -DefaultPercentage "TEST_VALUE" -Id "TEST_VALUE" -LastUpdate "TEST_VALUE" -LastUpdatedBy "TEST_VALUE" -OrgId "TEST_VALUE" -PrincipalId "TEST_VALUE" -PrincipalType "TEST_VALUE"
            #$NewObject | Should -BeOfType PrincipalRateLimitEntity
            #$NewObject.property | Should -Be 0
        }
    }
}
