#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RequiredEnum' {
    Context 'RequiredEnum' {
        It 'Initialize-RequiredEnum' {
            # a simple test to create an object
            #$NewObject = Initialize-RequiredEnum
            #$NewObject | Should -BeOfType RequiredEnum
            #$NewObject.property | Should -Be 0
        }
    }
}
