#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ResourceSetBindingAddMembersRequest' {
    Context 'ResourceSetBindingAddMembersRequest' {
        It 'Initialize-ResourceSetBindingAddMembersRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-ResourceSetBindingAddMembersRequest -Additions "TEST_VALUE"
            #$NewObject | Should -BeOfType ResourceSetBindingAddMembersRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
