#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ResourceSetResources' {
    Context 'ResourceSetResources' {
        It 'Initialize-ResourceSetResources' {
            # a simple test to create an object
            #$NewObject = Initialize-ResourceSetResources -Resources "TEST_VALUE" -Links "TEST_VALUE"
            #$NewObject | Should -BeOfType ResourceSetResources
            #$NewObject.property | Should -Be 0
        }
    }
}
