#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RiskPolicyRuleCondition' {
    Context 'RiskPolicyRuleCondition' {
        It 'Initialize-RiskPolicyRuleCondition' {
            # a simple test to create an object
            #$NewObject = Initialize-RiskPolicyRuleCondition -Behaviors "TEST_VALUE"
            #$NewObject | Should -BeOfType RiskPolicyRuleCondition
            #$NewObject.property | Should -Be 0
        }
    }
}
