#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'SamlApplicationSettingsSignOn' {
    Context 'SamlApplicationSettingsSignOn' {
        It 'Initialize-SamlApplicationSettingsSignOn' {
            # a simple test to create an object
            #$NewObject = Initialize-SamlApplicationSettingsSignOn -AcsEndpoints "TEST_VALUE" -AllowMultipleAcsEndpoints "TEST_VALUE" -AssertionSigned "TEST_VALUE" -AttributeStatements "TEST_VALUE" -Audience "TEST_VALUE" -AudienceOverride "TEST_VALUE" -AuthnContextClassRef "TEST_VALUE" -DefaultRelayState "TEST_VALUE" -Destination "TEST_VALUE" -DestinationOverride "TEST_VALUE" -DigestAlgorithm "TEST_VALUE" -HonorForceAuthn "TEST_VALUE" -IdpIssuer "TEST_VALUE" -InlineHooks "TEST_VALUE" -Recipient "TEST_VALUE" -RecipientOverride "TEST_VALUE" -RequestCompressed "TEST_VALUE" -ResponseSigned "TEST_VALUE" -SignatureAlgorithm "TEST_VALUE" -Slo "TEST_VALUE" -SpCertificate "TEST_VALUE" -SpIssuer "TEST_VALUE" -SsoAcsUrl "TEST_VALUE" -SsoAcsUrlOverride "TEST_VALUE" -SubjectNameIdFormat "TEST_VALUE" -SubjectNameIdTemplate "TEST_VALUE"
            #$NewObject | Should -BeOfType SamlApplicationSettingsSignOn
            #$NewObject.property | Should -Be 0
        }
    }
}
