#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'SecurityQuestionUserFactorAllOf' {
    Context 'SecurityQuestionUserFactorAllOf' {
        It 'Initialize-SecurityQuestionUserFactorAllOf' {
            # a simple test to create an object
            #$NewObject = Initialize-SecurityQuestionUserFactorAllOf -VarProfile "TEST_VALUE"
            #$NewObject | Should -BeOfType SecurityQuestionUserFactorAllOf
            #$NewObject.property | Should -Be 0
        }
    }
}
