#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'SmsTemplate' {
    Context 'SmsTemplate' {
        It 'Initialize-SmsTemplate' {
            # a simple test to create an object
            #$NewObject = Initialize-SmsTemplate -Created "TEST_VALUE" -Id "TEST_VALUE" -LastUpdated "TEST_VALUE" -Name "TEST_VALUE" -Template "TEST_VALUE" -Translations "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType SmsTemplate
            #$NewObject.property | Should -Be 0
        }
    }
}
