#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'UpdateDomain' {
    Context 'UpdateDomain' {
        It 'Initialize-UpdateDomain' {
            # a simple test to create an object
            #$NewObject = Initialize-UpdateDomain -BrandId "TEST_VALUE"
            #$NewObject | Should -BeOfType UpdateDomain
            #$NewObject.property | Should -Be 0
        }
    }
}
