#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'UserSchemaAttributePermission' {
    Context 'UserSchemaAttributePermission' {
        It 'Initialize-UserSchemaAttributePermission' {
            # a simple test to create an object
            #$NewObject = Initialize-UserSchemaAttributePermission -Action "TEST_VALUE" -Principal "TEST_VALUE"
            #$NewObject | Should -BeOfType UserSchemaAttributePermission
            #$NewObject.property | Should -Be 0
        }
    }
}
