#
# Okta Management
# Allows customers to easily access the Okta Management APIs
# Version: 3.0.0
# Contact: devex-public@okta.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#
BeforeAll {
    Import-Module -Name '.\src\Okta.PowerShell'
}

Describe -tag 'Okta.PowerShell' -name 'UserProfile' {
    Context 'Initialize-OktaUserProfile' {       
        It 'Test Min-Length warnings' {
            #if ($Email -and $Email.length -lt 5) {
            #    throw "invalid value for 'Email', the character length must be great than or equal to 5."
            #}

            { Initialize-OktaUserProfile -Email "abc" } | Should -Throw -ExpectedMessage "invalid value for 'Email', the character length must be great than or equal to 5."

        }
        It 'Test Max-Length warnings' {
            
            #if ($Email -and $Email.length -gt 100) {
            #    throw "invalid value for 'Email', the character length must be smaller than or equal to 100."
            #}

            # Generate a random string with 120 characters in PowerShell:
            $randomString = -join ((1..120) | ForEach-Object { ([char](Get-Random -Minimum 33 -Maximum 126)) })
            { Initialize-OktaUserProfile -Email $randomString } | Should -Throw -ExpectedMessage "invalid value for 'Email', the character length must be smaller than or equal to 100."
        }
    }
}
